/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        transparent: 'transparent',
        current: 'currentColor',
        white: 'var(--color-white)',
        'bg-primary': 'var(--color-bg-primary)',
        'bg-secondary': 'var(--color-bg-secondary)',
        'bg-card': 'var(--color-bg-card)',
        accent: 'var(--color-accent)',
        'accent-light': 'var(--color-accent-light)',
        'accent-foreground': 'var(--color-accent-foreground)',
        'accent-muted': 'var(--color-accent-muted)',
        primary: 'var(--color-primary)',
        'primary-hover': 'var(--color-primary-hover)',
        'primary-foreground': 'var(--color-primary-foreground)',
        'text-muted': 'var(--color-text-muted)',
        border: 'var(--color-border)',
        glass: 'var(--color-glass)',
        subtle: 'var(--color-subtle)',
        muted: 'var(--color-muted)',
        danger: 'var(--color-danger)',
        success: 'var(--color-success)',
        warning: 'var(--color-warning)',
        // Legacy mappings
        pblue: 'var(--color-pblue)',
        lblue: 'var(--color-lblue)',
        lorange: 'var(--color-lorange)',
        project: 'var(--color-project)',
        projectDesc: 'var(--color-projectDesc)',
      },
      fontFamily: {
        logofont: ['var(--font-logofont)'],
        headfont: ['var(--font-headfont)'],
        bodyfont: ['var(--font-bodyfont)'],
      },
      boxShadow: {
        glow: '0 1px 2px rgba(15, 23, 42, 0.06)',
        'glow-lg': '0 12px 28px rgba(15, 23, 42, 0.08)',
        card: '0 1px 3px rgba(15, 23, 42, 0.06)',
        'card-hover': '0 12px 28px rgba(15, 23, 42, 0.1)',
        projectCard: '0 1px 3px rgba(15, 23, 42, 0.06)',
      },
      typography: () => ({
        DEFAULT: {
          css: {
            maxWidth: '75ch',
            color: 'var(--color-white)',
            '--tw-prose-headings': 'var(--color-white)',
            '--tw-prose-links': 'var(--color-accent-foreground)',
            '--tw-prose-bold': 'var(--color-accent-foreground)',
            '--tw-prose-quotes': 'var(--color-text-muted)',
          },
        },
      }),
      animation: {
        'fade-in-up': 'fade-in-up 0.7s ease-out forwards',
        'fade-in': 'fade-in 0.6s ease-out forwards',
        'slide-in-right': 'slide-in-right 0.7s ease-out forwards',
        float: 'float 6s ease-in-out infinite',
      },
    },
    screens: {
      xs: '480px',
      sm: '640px',
      md: '768px',
      lg: '1024px',
      xl: '1280px',
      '2xl': '1536px',
      '3xl': '1920px',
    },
  },
  plugins: [require('@tailwindcss/typography')],
};
